In [2]:
from pathlib import Path
import xml.etree.ElementTree as ET

def print_entries_summary(file_name: str, max_entries: int | None = 5) -> None:
    """
    Print a simple summary of the first `max_entries` trace entries.
    Set max_entries=None to print all (could be very long).
    """
    notebook_dir = Path.cwd()
    traces_dir = notebook_dir.parent / "traces"
    file_path = traces_dir / file_name

    try:
        tree = ET.parse(file_path)
        root = tree.getroot()

        entries = root.find("entries")
        if entries is None:
            print("No <entries> section found.")
            return

        print("Game Entries")
        print("-" * 40)

        count = 0
        for entry in entries.findall("rts.TraceEntry"):
            time = entry.get("time", "?")
            print(f"Entry time = {time}")

            # --- Physical game state ---
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is not None:
                w = pgs.get("width", "?")
                h = pgs.get("height", "?")
                print(f"  Map: {w} x {h}")

                # Players
                players_node = pgs.find("players")
                if players_node is not None:
                    print("  Players:")
                    for p in players_node.findall("rts.Player"):
                        pid = p.get("ID", "?")
                        res = p.get("resources", "?")
                        print(f"    Player {pid}: resources={res}")

                # Units
                units_node = pgs.find("units")
                if units_node is not None:
                    print("  Units:")
                    for u in units_node.findall("rts.units.Unit"):
                        utype = u.get("type", "?")
                        uid = u.get("ID", "?")
                        player = u.get("player", "?")
                        x = u.get("x", "?")
                        y = u.get("y", "?")
                        hp = u.get("hitpoints", "?")
                        res = u.get("resources", "?")
                        print(f"    ID={uid}, type={utype}, player={player}, "
                              f"pos=({x},{y}), hp={hp}, resources={res}")

            # --- Actions ---
            actions_node = entry.find("actions")
            if actions_node is not None:
                print("  Actions:")
                any_action = False
                for a in actions_node.findall("action"):
                    any_action = True
                    uid = a.get("unitID", "?")
                    ua = a.find("UnitAction")
                    if ua is not None:
                        atype = ua.get("type", "?")
                        param = ua.get("parameter")
                        ux = ua.get("x")
                        uy = ua.get("y")
                        ut = ua.get("unitType")
                        extra = []
                        if param is not None:
                            extra.append(f"parameter={param}")
                        if ux is not None and uy is not None:
                            extra.append(f"target=({ux},{uy})")
                        if ut is not None:
                            extra.append(f"unitType={ut}")
                        extra_str = ", ".join(extra) if extra else ""
                        print(f"    unitID={uid}, type={atype}"
                              + (f", {extra_str}" if extra_str else ""))
                if not any_action:
                    print("    (no actions)")
            print("-" * 40)

            count += 1
            if max_entries is not None and count >= max_entries:
                break

    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except ET.ParseError as e:
        print(f"XML parse error: {e}")
    except OSError as e:
        print(f"Error reading file: {e}")

# Example call:
print_entries_summary("AggrobotAStarPathFindingVsRandomBiasedAI-0-0.xml", max_entries=5)

Game Entries
----------------------------------------
Entry time = 0
  Map: 8 x 8
  Players:
    Player 0: resources=5
    Player 1: resources=5
  Units:
    ID=0, type=Resource, player=-1, pos=(0,0), hp=1, resources=20
    ID=1, type=Resource, player=-1, pos=(7,7), hp=1, resources=20
    ID=2, type=Base, player=0, pos=(2,1), hp=10, resources=0
    ID=3, type=Base, player=1, pos=(5,6), hp=10, resources=0
  Actions:
    (no actions)
----------------------------------------
Entry time = 0
  Map: 8 x 8
  Players:
    Player 0: resources=5
    Player 1: resources=5
  Units:
    ID=0, type=Resource, player=-1, pos=(0,0), hp=1, resources=20
    ID=1, type=Resource, player=-1, pos=(7,7), hp=1, resources=20
    ID=2, type=Base, player=0, pos=(2,1), hp=10, resources=0
    ID=3, type=Base, player=1, pos=(5,6), hp=10, resources=0
  Actions:
    unitID=2, type=4, parameter=0, unitType=Worker
    unitID=3, type=4, parameter=1, unitType=Worker
----------------------------------------
Entry time = 50
  Map: 8 x 8
  Players:
    Player 0: resources=4
    Player 1: resources=4
  Units:
    ID=0, type=Resource, player=-1, pos=(0,0), hp=1, resources=20
    ID=1, type=Resource, player=-1, pos=(7,7), hp=1, resources=20
    ID=2, type=Base, player=0, pos=(2,1), hp=10, resources=0
    ID=3, type=Base, player=1, pos=(5,6), hp=10, resources=0
    ID=4, type=Worker, player=0, pos=(2,0), hp=1, resources=0
    ID=5, type=Worker, player=1, pos=(6,6), hp=1, resources=0
  Actions:
    unitID=4, type=1, parameter=3
    unitID=2, type=4, parameter=3, unitType=Worker
    unitID=3, type=4, parameter=0, unitType=Worker
    unitID=5, type=0, parameter=10
----------------------------------------
Entry time = 60
  Map: 8 x 8
  Players:
    Player 0: resources=4
    Player 1: resources=4
  Units:
    ID=0, type=Resource, player=-1, pos=(0,0), hp=1, resources=20
    ID=1, type=Resource, player=-1, pos=(7,7), hp=1, resources=20
    ID=2, type=Base, player=0, pos=(2,1), hp=10, resources=0
    ID=3, type=Base, player=1, pos=(5,6), hp=10, resources=0
    ID=4, type=Worker, player=0, pos=(1,0), hp=1, resources=0
    ID=5, type=Worker, player=1, pos=(6,6), hp=1, resources=0
  Actions:
    unitID=4, type=2, parameter=3
    unitID=5, type=0, parameter=10
----------------------------------------
Entry time = 70
  Map: 8 x 8
  Players:
    Player 0: resources=4
    Player 1: resources=4
  Units:
    ID=0, type=Resource, player=-1, pos=(0,0), hp=1, resources=20
    ID=1, type=Resource, player=-1, pos=(7,7), hp=1, resources=20
    ID=2, type=Base, player=0, pos=(2,1), hp=10, resources=0
    ID=3, type=Base, player=1, pos=(5,6), hp=10, resources=0
    ID=4, type=Worker, player=0, pos=(1,0), hp=1, resources=0
    ID=5, type=Worker, player=1, pos=(6,6), hp=1, resources=0
  Actions:
    unitID=5, type=0, parameter=10
----------------------------------------

In [13]:
from pathlib import Path
import xml.etree.ElementTree as ET

def print_unit_type_table(file_name: str) -> None:
    notebook_dir = Path.cwd()
    traces_dir = notebook_dir.parent / "traces"
    file_path = traces_dir / file_name

    try:
        tree = ET.parse(file_path)
        root = tree.getroot()

        # Find the UnitTypeTable node
        utt = root.find(".//rts.units.UnitTypeTable")

        if utt is None:
            print("No <rts.units.UnitTypeTable> found in XML.")
            return

        print("Unit type Table")
        print("-" * 40)

        # Iterate over all UnitType elements inside the table
        for ut in utt.findall("rts.units.UnitType"):
            attrs = ut.attrib  # dict of attributes
            name = attrs.get("name", "<no-name>")
            print(f"UnitType: {name}")
            for k, v in attrs.items():
                if k == "name":
                    continue
                print(f"  {k}: {v}")
            print()  # blank line between unit types

    except FileNotFoundError:
        print(f"File not found: {file_path}")
    except ET.ParseError as e:
        print(f"XML parse error: {e}")
    except OSError as e:
        print(f"Error reading file: {e}")

# Call with your file
print_unit_type_table("AggrobotAStarPathFindingVsRandomBiasedAI-0-0.xml")

Unit type Table
----------------------------------------
UnitType: Resource
  ID: 0
  cost: 1
  hp: 1
  minDamage: 1
  maxDamage: 1
  attackRange: 1
  produceTime: 10
  moveTime: 10
  attackTime: 10
  harvestTime: 10
  returnTime: 10
  harvestAmount: 1
  sightRadius: 0
  isResource: true
  isStockpile: false
  canHarvest: false
  canMove: false
  canAttack: false

UnitType: Base
  ID: 1
  cost: 10
  hp: 10
  minDamage: 1
  maxDamage: 1
  attackRange: 1
  produceTime: 250
  moveTime: 10
  attackTime: 10
  harvestTime: 10
  returnTime: 10
  harvestAmount: 1
  sightRadius: 5
  isResource: false
  isStockpile: true
  canHarvest: false
  canMove: false
  canAttack: false

UnitType: Barracks
  ID: 2
  cost: 5
  hp: 4
  minDamage: 1
  maxDamage: 1
  attackRange: 1
  produceTime: 200
  moveTime: 10
  attackTime: 10
  harvestTime: 10
  returnTime: 10
  harvestAmount: 1
  sightRadius: 3
  isResource: false
  isStockpile: false
  canHarvest: false
  canMove: false
  canAttack: false

UnitType: Worker
  ID: 3
  cost: 1
  hp: 1
  minDamage: 1
  maxDamage: 1
  attackRange: 1
  produceTime: 50
  moveTime: 10
  attackTime: 5
  harvestTime: 20
  returnTime: 10
  harvestAmount: 1
  sightRadius: 3
  isResource: false
  isStockpile: false
  canHarvest: true
  canMove: true
  canAttack: true

UnitType: Light
  ID: 4
  cost: 2
  hp: 4
  minDamage: 2
  maxDamage: 2
  attackRange: 1
  produceTime: 80
  moveTime: 8
  attackTime: 5
  harvestTime: 10
  returnTime: 10
  harvestAmount: 1
  sightRadius: 2
  isResource: false
  isStockpile: false
  canHarvest: false
  canMove: true
  canAttack: true

UnitType: Heavy
  ID: 5
  cost: 2
  hp: 4
  minDamage: 4
  maxDamage: 4
  attackRange: 1
  produceTime: 120
  moveTime: 12
  attackTime: 5
  harvestTime: 10
  returnTime: 10
  harvestAmount: 1
  sightRadius: 2
  isResource: false
  isStockpile: false
  canHarvest: false
  canMove: true
  canAttack: true

UnitType: Ranged
  ID: 6
  cost: 2
  hp: 1
  minDamage: 1
  maxDamage: 1
  attackRange: 3
  produceTime: 100
  moveTime: 10
  attackTime: 5
  harvestTime: 10
  returnTime: 10
  harvestAmount: 1
  sightRadius: 3
  isResource: false
  isStockpile: false
  canHarvest: false
  canMove: true
  canAttack: true

In [2]:
from pathlib import Path
import math
import xml.etree.ElementTree as ET

# ========= GLOBAL TRACE DIRECTORY =========
TRACE_DIR = "traces/12x12"   # change this once to switch directory

def get_trace_path(file_name: str) -> Path:
    notebook_dir = Path.cwd()
    traces_dir = notebook_dir.parent / TRACE_DIR
    return traces_dir / file_name

# ========= GLOBAL OUTPUT BUFFER =========
log_lines = []

def log(msg: str) -> None:
    log_lines.append(msg)

# ========= HELPERS =========

def build_unit_cost_table(root) -> dict:
    utt = root.find(".//rts.units.UnitTypeTable")
    cost_table = {}
    if utt is not None:
        for ut in utt.findall("rts.units.UnitType"):
            name = ut.get("name")
            cost = ut.get("cost")
            if name is not None and cost is not None:
                cost_table[name] = int(cost)
    return cost_table

def count_units_built(root, player_id: str) -> dict:
    entries = root.find("entries")
    counts = {}
    if entries is None:
        return counts

    seen_ids = set()
    for entry in entries.findall("rts.TraceEntry"):
        pgs = entry.find("rts.PhysicalGameState")
        if pgs is None:
            continue
        units = pgs.find("units")
        if units is None:
            continue

        for u in units.findall("rts.units.Unit"):
            if u.get("player") != player_id:
                continue
            uid = u.get("ID")
            if uid is None or uid in seen_ids:
                continue
            seen_ids.add(uid)
            utype = u.get("type")
            if utype is None:
                continue
            counts[utype] = counts.get(utype, 0) + 1
    return counts

def get_player_resources(entry, player_id: str) -> int:
    pgs = entry.find("rts.PhysicalGameState")
    if pgs is None:
        return 0
    players = pgs.find("players")
    if players is None:
        return 0
    for p in players.findall("rts.Player"):
        if p.get("ID") == player_id:
            return int(p.get("resources", "0"))
    return 0

def total_map_resources(root) -> int:
    entries = root.find("entries")
    if entries is None:
        return 0
    first_entry = next(iter(entries.findall("rts.TraceEntry")), None)
    if first_entry is None:
        return 0

    pgs = first_entry.find("rts.PhysicalGameState")
    if pgs is None:
        return 0
    units = pgs.find("units")
    if units is None:
        return 0

    total = 0
    for u in units.findall("rts.units.Unit"):
        if u.get("type") == "Resource" and u.get("player") == "-1":
            total += int(u.get("resources", "0"))
    return total

# ========= MAIN ANALYSIS FUNCTIONS =========

def first_barracks_time(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        first_time = None
        for entry in entries.findall("rts.TraceEntry"):
            t = entry.get("time")
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units = pgs.find("units")
            if units is None:
                continue

            for u in units.findall("rts.units.Unit"):
                if u.get("type") == "Barracks" and u.get("player") == player_id:
                    first_time = t
                    break
            if first_time is not None:
                break

        if first_time is None:
            log(f"Player {player_id} never has a Barracks in this trace.")
        else:
            log(f"Player {player_id} first has a Barracks at trace time = {first_time}")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def barracks_count(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        barracks_ids = set()
        for entry in entries.findall("rts.TraceEntry"):
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units = pgs.find("units")
            if units is None:
                continue

            for u in units.findall("rts.units.Unit"):
                if u.get("type") == "Barracks" and u.get("player") == player_id:
                    uid = u.get("ID")
                    if uid is not None:
                        barracks_ids.add(uid)

        log(f"Player {player_id} built {len(barracks_ids)} Barracks in this trace.")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def harvested_resources(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()

        cost_table = build_unit_cost_table(root)
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        all_entries = entries.findall("rts.TraceEntry")
        if not all_entries:
            log("Trace has no entries.")
            return

        first_entry = all_entries[0]
        last_entry = all_entries[-1]

        r_initial = get_player_resources(first_entry, player_id)
        r_final = get_player_resources(last_entry, player_id)

        built_counts = count_units_built(root, player_id)

        total_spent = 0
        for unit_type, n in built_counts.items():
            cost = cost_table.get(unit_type, 0)
            total_spent += cost * n

        harvested = (r_final - r_initial) + total_spent

        log(f"Player {player_id} approximately harvested {harvested} resources in this game.")
        log(f"  (initial={r_initial}, final={r_final}, spent={total_spent})")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def harvested_resources_percent(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()

        cost_table = build_unit_cost_table(root)
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        all_entries = entries.findall("rts.TraceEntry")
        if not all_entries:
            log("Trace has no entries.")
            return

        first_entry = all_entries[0]
        last_entry = all_entries[-1]

        r_initial = get_player_resources(first_entry, player_id)
        r_final = get_player_resources(last_entry, player_id)

        built_counts = count_units_built(root, player_id)
        total_spent = 0
        for unit_type, n in built_counts.items():
            cost = cost_table.get(unit_type, 0)
            total_spent += cost * n

        harvested = (r_final - r_initial) + total_spent
        total_initial_resources = total_map_resources(root)

        if total_initial_resources > 0:
            percent = 100.0 * harvested / total_initial_resources
        else:
            percent = 0.0

        log(f"Total initial resources on map: {total_initial_resources}")
        log(f"Player {player_id} approx harvested: {harvested}")
        log(f"Player {player_id} harvested ~{percent:.2f}% of all resources on the map.")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def workers_built(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        seen_ids = set()
        workers_built_count = 0

        for entry in entries.findall("rts.TraceEntry"):
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units = pgs.find("units")
            if units is None:
                continue

            for u in units.findall("rts.units.Unit"):
                if u.get("player") != player_id:
                    continue
                if u.get("type") != "Worker":
                    continue
                uid = u.get("ID")
                if uid is None or uid in seen_ids:
                    continue
                seen_ids.add(uid)
                workers_built_count += 1

        log(f"Player {player_id} built {workers_built_count} Workers in this trace.")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def workers_built_milestones(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    milestones = [100, 200, 400, 800]
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        milestone_counts = {m: None for m in milestones}
        seen_ids = set()
        workers_built_count = 0

        for entry in entries.findall("rts.TraceEntry"):
            t_str = entry.get("time")
            if t_str is None:
                continue
            t = int(t_str)

            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units = pgs.find("units")
            if units is None:
                continue

            for u in units.findall("rts.units.Unit"):
                if u.get("player") != player_id:
                    continue
                if u.get("type") != "Worker":
                    continue
                uid = u.get("ID")
                if uid is None or uid in seen_ids:
                    continue
                seen_ids.add(uid)
                workers_built_count += 1

            for m in milestones:
                if milestone_counts[m] is None and t >= m:
                    milestone_counts[m] = workers_built_count

        log(f"Workers built by player {player_id} at milestones (cumulative):")
        for m in milestones:
            if milestone_counts[m] is not None:
                log(f"  time >= {m}: {milestone_counts[m]} Workers")
            else:
                log(f"  time >= {m}: (milestone not reached in this trace)")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def game_length_ticks(file_name: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        all_entries = entries.findall("rts.TraceEntry")
        if not all_entries:
            log("Trace has no entries.")
            return

        last_entry = all_entries[-1]
        t_str = last_entry.get("time", "0")
        try:
            t = int(t_str)
        except ValueError:
            t = 0

        log(f"Game length: {t} ticks")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def player_won(file_name: str, player_id: str, enemy_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        all_entries = entries.findall("rts.TraceEntry")
        if not all_entries:
            log("Trace has no entries.")
            return

        last_entry = all_entries[-1]
        pgs = last_entry.find("rts.PhysicalGameState")
        if pgs is None:
            log("No PhysicalGameState in last entry.")
            return

        units = pgs.find("units")
        if units is None:
            log("No units section in last entry.")
            return

        has_me = False
        has_enemy = False
        for u in units.findall("rts.units.Unit"):
            p = u.get("player")
            if p == player_id:
                has_me = True
            elif p == enemy_id:
                has_enemy = True

        if has_me and not has_enemy:
            log(f"Player {player_id}: WIN")
        elif has_enemy and not has_me:
            log(f"Player {player_id}: LOSS")
        else:
            log(f"Player {player_id}: DRAW/UNDECIDED (both or neither have units)")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def combat_units_built(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        seen_ids = set()
        light = heavy = ranged = 0

        for entry in entries.findall("rts.TraceEntry"):
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units = pgs.find("units")
            if units is None:
                continue

            for u in units.findall("rts.units.Unit"):
                if u.get("player") != player_id:
                    continue
                utype = u.get("type")
                if utype not in ("Light", "Heavy", "Ranged"):
                    continue
                uid = u.get("ID")
                if uid is None or uid in seen_ids:
                    continue
                seen_ids.add(uid)
                if utype == "Light":
                    light += 1
                elif utype == "Heavy":
                    heavy += 1
                elif utype == "Ranged":
                    ranged += 1

        log(f"Player {player_id} built in total:")
        log(f"  Light units : {light}")
        log(f"  Heavy units : {heavy}")
        log(f"  Ranged units: {ranged}")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def first_attack_time(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        first_time = None
        for entry in entries.findall("rts.TraceEntry"):
            t = entry.get("time")
            if t is None:
                continue

            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units_node = pgs.find("units")
            if units_node is None:
                continue

            unit_player = {}
            for u in units_node.findall("rts.units.Unit"):
                uid = u.get("ID")
                p = u.get("player")
                if uid is not None:
                    unit_player[uid] = p

            actions_node = entry.find("actions")
            if actions_node is None:
                continue

            for a in actions_node.findall("action"):
                uid = a.get("unitID")
                if uid is None:
                    continue
                if unit_player.get(uid) != player_id:
                    continue
                ua = a.find("UnitAction")
                if ua is None:
                    continue
                if ua.get("type") == "5":
                    first_time = t
                    break
            if first_time is not None:
                break

        if first_time is None:
            log(f"Player {player_id} never issues an ATTACK action in this trace.")
        else:
            log(f"Player {player_id} first ATTACK action at trace time = {first_time}")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def total_attacks(file_name: str, player_id: str) -> int:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return 0

        attack_count = 0
        for entry in entries.findall("rts.TraceEntry"):
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units_node = pgs.find("units")
            if units_node is None:
                continue

            unit_player = {}
            for u in units_node.findall("rts.units.Unit"):
                uid = u.get("ID")
                p = u.get("player")
                if uid is not None:
                    unit_player[uid] = p

            actions_node = entry.find("actions")
            if actions_node is None:
                continue

            for a in actions_node.findall("action"):
                uid = a.get("unitID")
                if uid is None:
                    continue
                if unit_player.get(uid) != player_id:
                    continue
                ua = a.find("UnitAction")
                if ua is None:
                    continue
                if ua.get("type") == "5":
                    attack_count += 1

        log(f"Player {player_id} issued {attack_count} ATTACK actions in this trace.")
        return attack_count

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")
    return 0

def attacks_per_trace(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        all_entries = entries.findall("rts.TraceEntry")
        num_entries = len(all_entries)
        if num_entries == 0:
            log("Trace has no entries.")
            return

        total_attacks_count = 0
        for entry in all_entries:
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units_node = pgs.find("units")
            if units_node is None:
                continue

            unit_player = {}
            for u in units_node.findall("rts.units.Unit"):
                uid = u.get("ID")
                p = u.get("player")
                if uid is not None:
                    unit_player[uid] = p

            actions_node = entry.find("actions")
            if actions_node is None:
                continue

            for a in actions_node.findall("action"):
                uid = a.get("unitID")
                if uid is None:
                    continue
                if unit_player.get(uid) != player_id:
                    continue
                ua = a.find("UnitAction")
                if ua is None:
                    continue
                if ua.get("type") == "5":
                    total_attacks_count += 1

        attacks_per_entry = total_attacks_count / num_entries
        log(f"Player {player_id} issued {total_attacks_count} ATTACK actions in total.")
        log(f"Number of trace entries: {num_entries}")
        log(f"Average ATTACKs per trace entry: {attacks_per_entry:.4f}")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def max_attacks_in_single_trace(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        max_attacks = 0
        max_time = None

        for entry in entries.findall("rts.TraceEntry"):
            t = entry.get("time")
            if t is None:
                continue

            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units_node = pgs.find("units")
            if units_node is None:
                continue

            unit_player = {}
            for u in units_node.findall("rts.units.Unit"):
                uid = u.get("ID")
                p = u.get("player")
                if uid is not None:
                    unit_player[uid] = p

            actions_node = entry.find("actions")
            if actions_node is None:
                continue

            attacks_this_entry = 0
            for a in actions_node.findall("action"):
                uid = a.get("unitID")
                if uid is None:
                    continue
                if unit_player.get(uid) != player_id:
                    continue
                ua = a.find("UnitAction")
                if ua is None:
                    continue
                if ua.get("type") == "5":
                    attacks_this_entry += 1

            if attacks_this_entry > max_attacks:
                max_attacks = attacks_this_entry
                max_time = t

        if max_time is None:
            log(f"Player {player_id} never issues an ATTACK action in this trace.")
        else:
            log(f"Max ATTACKs by player {player_id} in a single trace entry: {max_attacks}")
            log(f"Occurred at trace time = {max_time}")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def avg_distance_to_enemy_base(file_name: str, player_id: str, enemy_id: str) -> None:
    file_path = get_trace_path(file_name)
    milestones = [100, 200, 400, 800]
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        all_entries = entries.findall("rts.TraceEntry")
        if not all_entries:
            log("Trace has no entries.")
            return

        enemy_base_pos = None
        for entry in all_entries:
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units = pgs.find("units")
            if units is None:
                continue
            for u in units.findall("rts.units.Unit"):
                if u.get("type") == "Base" and u.get("player") == enemy_id:
                    x = u.get("x")
                    y = u.get("y")
                    if x is not None and y is not None:
                        enemy_base_pos = (int(x), int(y))
                        break
            if enemy_base_pos is not None:
                break

        if enemy_base_pos is None:
            log(f"Could not find enemy base (player {enemy_id} Base) in trace.")
            return

        ex, ey = enemy_base_pos
        results = {m: (None, None) for m in milestones}

        for m in milestones:
            entry_for_m = None
            for entry in all_entries:
                t_str = entry.get("time")
                if t_str is None:
                    continue
                t = int(t_str)
                if t >= m:
                    entry_for_m = (t, entry)
                    break
            if entry_for_m is None:
                continue

            t, entry = entry_for_m
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                continue
            units = pgs.find("units")
            if units is None:
                continue

            distances = []
            for u in units.findall("rts.units.Unit"):
                if u.get("player") != player_id:
                    continue
                ux = u.get("x")
                uy = u.get("y")
                if ux is None or uy is None:
                    continue
                ux = int(ux)
                uy = int(uy)
                d = math.sqrt((ux - ex) ** 2 + (uy - ey) ** 2)
                distances.append(d)

            if distances:
                avg_d = sum(distances) / len(distances)
                results[m] = (avg_d, t)
            else:
                results[m] = (None, t)

        log(f"Average distance of player-{player_id} units to enemy base (player {enemy_id} Base):")
        log(f"Enemy base at: {enemy_base_pos}")
        for m in milestones:
            avg_d, t = results[m]
            if t is None:
                log(f"  time >= {m}: milestone not reached in this trace")
            elif avg_d is None:
                log(f"  time >= {m} (first time={t}): no player-{player_id} units present")
            else:
                log(f"  time >= {m} (first time={t}): avg distance = {avg_d:.3f}")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

def combat_units_milestones(file_name: str, player_id: str) -> None:
    file_path = get_trace_path(file_name)
    milestones = [100, 200, 400, 800]
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        entries = root.find("entries")
        if entries is None:
            log("No <entries> section found.")
            return

        all_entries = entries.findall("rts.TraceEntry")
        if not all_entries:
            log("Trace has no entries.")
            return

        results = {}
        for m in milestones:
            chosen = None
            for entry in all_entries:
                t_str = entry.get("time")
                if t_str is None:
                    continue
                t = int(t_str)
                if t >= m:
                    chosen = (t, entry)
                    break
            if chosen is None:
                results[m] = None
                continue

            t, entry = chosen
            pgs = entry.find("rts.PhysicalGameState")
            if pgs is None:
                results[m] = (t, 0, 0, 0)
                continue
            units = pgs.find("units")
            if units is None:
                results[m] = (t, 0, 0, 0)
                continue

            light = heavy = ranged = 0
            for u in units.findall("rts.units.Unit"):
                if u.get("player") != player_id:
                    continue
                utype = u.get("type")
                if utype == "Light":
                    light += 1
                elif utype == "Heavy":
                    heavy += 1
                elif utype == "Ranged":
                    ranged += 1

            results[m] = (t, light, heavy, ranged)

        log(f"Player {player_id} combat units at milestones:")
        for m in milestones:
            val = results[m]
            if val is None:
                log(f"  time >= {m}: milestone not reached in this trace")
            else:
                t, light, heavy, ranged = val
                log(f"  time >= {m} (first time={t}): Light={light}, Heavy={heavy}, Ranged={ranged}")

    except FileNotFoundError:
        log(f"File not found: {file_path}")
    except ET.ParseError as e:
        log(f"XML parse error: {e}")
    except OSError as e:
        log(f"Error reading file: {e}")

# ========= MASTER CALLER =========

def analyze_trace(file_name: str, player_id: str, enemy_id: str = "1") -> Path:
    global log_lines
    log_lines = []

    log(f"=== Analyzing trace: {file_name}, player {player_id} vs {enemy_id} ===")
    first_barracks_time(file_name, player_id)
    barracks_count(file_name, player_id)
    combat_units_milestones(file_name, player_id)
    avg_distance_to_enemy_base(file_name, player_id, enemy_id)
    max_attacks_in_single_trace(file_name, player_id)
    attacks_per_trace(file_name, player_id)
    first_attack_time(file_name, player_id)
    combat_units_built(file_name, player_id)
    game_length_ticks(file_name)
    player_won(file_name, player_id, enemy_id)
    workers_built_milestones(file_name, player_id)
    workers_built(file_name, player_id)
    harvested_resources(file_name, player_id)
    harvested_resources_percent(file_name, player_id)

    # use just the directory name + generic suffix
    dir_name = Path(TRACE_DIR).name
    out_name = f"analyzed_traces_{dir_name}_ALL.txt"
    out_path = Path.cwd() / out_name

    with out_path.open("a", encoding="utf-8") as f:
        for line in log_lines:
            f.write(line + "\n")
        f.write("\n")

    return out_path

def infer_players_from_name(file_name: str):
    """
    If name starts with 'tiamat' (case-insensitive): player_id = '1', enemy_id = '0'
    If name starts with 'mayari'                     : player_id = '0', enemy_id = '1'
    Else default: player_id = '0', enemy_id = '1'
    """
    lower = file_name.lower()
    if lower.startswith("tiamat"):
        return "1", "0"
    elif lower.startswith("mayari"):
        return "0", "1"
    else:
        return "0", "1"

# ========= DRIVER: ANALYZE ALL TRACES IN DIRECTORY =========

def analyze_all_traces_in_dir():
    traces_dir = Path.cwd().parent / TRACE_DIR
    dir_name = Path(TRACE_DIR).name
    out_name = f"analyzed_traces_{dir_name}_ALL.txt"
    out_path = Path.cwd() / out_name

    # start from a clean file
    if out_path.exists():
        out_path.unlink()

    # analyze every .xml trace in the directory
    for path in sorted(traces_dir.glob("*.xml")):
        file_name = path.name
        player_id, enemy_id = infer_players_from_name(file_name)
        analyze_trace(file_name, player_id=player_id, enemy_id=enemy_id)

    print(f"Finished analyzing all traces in {traces_dir}")
    print(f"Results written to {out_path}")

# Run this to process all traces in TRACE_DIR
analyze_all_traces_in_dir()

Finished analyzing all traces in C:\Users\bikep\IdeaProjects\myMicroRTSBot\traces\12x12
Results written to C:\Users\bikep\IdeaProjects\myMicroRTSBot\pythonCode\analyzed_traces_12x12_ALL.txt

In [3]:
import re
from pathlib import Path

log_path = Path("analyzed_traces_12x12_ALL.txt")  # adjust if needed

with log_path.open("r", encoding="utf-8") as f:
    full_text = f.read().strip()

blocks = [b.strip() for b in full_text.split("\n\n") if b.strip()]

COLS = [
    "FirstBarracks",
    "NumBarracks",
    "Light100",
    "Heavy100",
    "Ranged100",
    "Light200",
    "Heavy200",
    "Ranged200",
    "Light400",
    "Heavy400",
    "Ranged400",
    "Light800",
    "Heavy800",
    "Ranged800",
    "AvgDist100",
    "AvgDist200",
    "AvgDist400",
    "AvgDist800",
    "MaxAttacksSingleTrace",
    "TimeMaxAttacks",
    "TotalAttacks",
    "AvgAttacksPerTrace",
    "FirstAttackTime",
    "TotalLight",
    "TotalHeavy",
    "TotalRanged",
    "GameLength",
    "PlayerWin",
    "Workers100",
    "Workers200",
    "Workers400",
    "Workers800",
    "TotalWorkers",
    "PercentMapHarvested",
]

MILESTONES = [100, 200, 400, 800]

def carry_forward_milestones(data: dict) -> None:
    # Workers: carry forward, then fall back to TotalWorkers
    last = None
    for t in MILESTONES:
        key = f"Workers{t}"
        v = data.get(key, -1)
        if v != -1:
            last = v
        else:
            if last is not None:
                data[key] = last
    total_workers = data.get("TotalWorkers", -1)
    if total_workers != -1:
        for t in MILESTONES:
            key = f"Workers{t}"
            if data.get(key, -1) == -1:
                data[key] = total_workers
    else:
        for t in MILESTONES:
            key = f"Workers{t}"
            if data.get(key, -1) == -1:
                data[key] = 0

    # Combat units: Light / Heavy / Ranged
    for unit in ("Light", "Heavy", "Ranged"):
        last = None
        for t in MILESTONES:
            key = f"{unit}{t}"
            v = data.get(key, -1)
            if v != -1:
                last = v
            else:
                if last is not None:
                    data[key] = last
        total_key = f"Total{unit}"
        total_val = data.get(total_key, -1)
        if total_val != -1:
            for t in MILESTONES:
                key = f"{unit}{t}"
                if data.get(key, -1) == -1:
                    data[key] = total_val
        else:
            for t in MILESTONES:
                key = f"{unit}{t}"
                if data.get(key, -1) == -1:
                    data[key] = 0

    # AvgDist at milestones: carry forward last seen distance
    last = None
    for t in MILESTONES:
        key = f"AvgDist{t}"
        v = data.get(key, -1)
        if v != -1:
            last = v
        else:
            if last is not None:
                data[key] = last
    # If still missing at all milestones, set to 0
    for t in MILESTONES:
        key = f"AvgDist{t}"
        if data.get(key, -1) == -1:
            data[key] = 0.0


def parse_block(block: str) -> dict:
    first_line = block.splitlines()[0].strip()
    m_pid = re.search(r"player\s+(\d+)\s+vs\s+(\d+)", first_line)
    if m_pid:
        player_id = int(m_pid.group(1))
    else:
        player_id = 0

    data = {k: -1 for k in COLS}
    # default: if no barracks is ever seen, keep FirstBarracks = 0
    data["FirstBarracks"] = 0

    lines = block.splitlines()
    for line in lines:
        line = line.strip()

        m = re.search(rf"Player {player_id} first has a Barracks at trace time = (\d+)", line)
        if m:
            data["FirstBarracks"] = int(m.group(1))

        m = re.search(rf"Player {player_id} built (\d+) Barracks", line)
        if m:
            data["NumBarracks"] = int(m.group(1))

        m = re.search(r"time >= (\d+) \(first time=\d+\): Light=(\d+), Heavy=(\d+), Ranged=(\d+)", line)
        if m:
            t, L, H, R = map(int, m.groups())
            if t in (100, 200, 400, 800):
                data[f"Light{t}"] = L
                data[f"Heavy{t}"] = H
                data[f"Ranged{t}"] = R

        m = re.search(r"time >= (\d+) \(first time=\d+\): avg distance = ([0-9.]+)", line)
        if m:
            t = int(m.group(1))
            if t in (100, 200, 400, 800):
                data[f"AvgDist{t}"] = float(m.group(2))

        m = re.search(rf"Max ATTACKs by player {player_id} in a single trace entry: (\d+)", line)
        if m:
            data["MaxAttacksSingleTrace"] = int(m.group(1))

        m = re.search(r"Occurred at trace time = (\d+)", line)
        if m:
            data["TimeMaxAttacks"] = int(m.group(1))

        m = re.search(rf"Player {player_id} issued (\d+) ATTACK actions in total", line)
        if m:
            data["TotalAttacks"] = int(m.group(1))

        m = re.search(r"Average ATTACKs per trace entry: ([0-9.]+)", line)
        if m:
            data["AvgAttacksPerTrace"] = float(m.group(1))

        m = re.search(rf"Player {player_id} first ATTACK action at trace time = (\d+)", line)
        if m:
            data["FirstAttackTime"] = int(m.group(1))

        m = re.search(r"Light units\s*:\s*(\d+)", line)
        if m:
            data["TotalLight"] = int(m.group(1))
        m = re.search(r"Heavy units\s*:\s*(\d+)", line)
        if m:
            data["TotalHeavy"] = int(m.group(1))
        m = re.search(r"Ranged units\s*:\s*(\d+)", line)
        if m:
            data["TotalRanged"] = int(m.group(1))

        m = re.search(r"Game length:\s*(\d+)\s*ticks", line)
        if m:
            data["GameLength"] = int(m.group(1))

        if f"Player {player_id}: WIN" in line:
            data["PlayerWin"] = 1
        elif f"Player {player_id}: LOSS" in line:
            data["PlayerWin"] = 0
        elif f"Player {player_id}: DRAW" in line:
            data["PlayerWin"] = 0.5

        m = re.search(r"time >= (\d+): (\d+) Workers", line)
        if m:
            t = int(m.group(1))
            if t in (100, 200, 400, 800):
                data[f"Workers{t}"] = int(m.group(2))

        m = re.search(rf"Player {player_id} built (\d+) Workers in this trace", line)
        if m:
            data["TotalWorkers"] = int(m.group(1))

        m = re.search(rf"Player {player_id} harvested ~([0-9.]+)% of all resources", line)
        if m:
            data["PercentMapHarvested"] = float(m.group(1))

    # fix milestones so no -1 remains in workers / combat units / avg distances
    carry_forward_milestones(data)

    # also remove -1 from other numeric fields (turn into 0)
    for k in COLS:
        if isinstance(data[k], (int, float)) and data[k] == -1:
            data[k] = 0

    return data

rows = [parse_block(b) for b in blocks]

print(",".join(COLS))
for d in rows:
    print(",".join(str(d[k]) for k in COLS))

FirstBarracks,NumBarracks,Light100,Heavy100,Ranged100,Light200,Heavy200,Ranged200,Light400,Heavy400,Ranged400,Light800,Heavy800,Ranged800,AvgDist100,AvgDist200,AvgDist400,AvgDist800,MaxAttacksSingleTrace,TimeMaxAttacks,TotalAttacks,AvgAttacksPerTrace,FirstAttackTime,TotalLight,TotalHeavy,TotalRanged,GameLength,PlayerWin,Workers100,Workers200,Workers400,Workers800,TotalWorkers,PercentMapHarvested
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.399,8.399,8.399,1,230,12,0.0504,230,0,0,0,305,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.399,8.399,8.399,1,230,12,0.0504,230,0,0,0,305,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.499,8.046,8.046,8.046,1,190,12,0.0519,190,0,0,0,315,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.106,6.685,6.685,6.685,1,170,12,0.0472,170,0,0,0,325,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.978,5.865,5.865,5.865,1,170,13,0.0695,170,0,0,0,335,1,3,5,5,5,7,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.24,6.24,6.24,6.24,1,130,12,0.0566,130,0,0,0,335,1,3,5,5,5,7,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.304,5.076,5.076,5.076,2,140,14,0.0859,130,0,0,0,325,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.992,5.668,5.668,5.668,2,180,12,0.0784,150,0,0,0,265,1,3,5,5,5,6,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.919,5.682,5.682,5.682,1,170,12,0.0656,170,0,0,0,295,1,3,5,5,5,6,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.205,6.676,6.676,6.676,2,220,12,0.0622,190,0,0,0,250,1,3,5,5,5,6,23.75
530,1,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.899,8.593,8.593,2,450,24,0.0642,230,1,0,0,785,1,3,5,9,9,16,37.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.899,8.899,8.899,2,345,19,0.0792,230,0,0,0,395,1,3,5,5,5,8,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.499,7.526,7.285,7.285,1,250,20,0.0725,250,0,0,0,525,1,3,5,9,9,11,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.106,6.885,6.037,6.037,2,430,20,0.0738,180,0,0,0,475,1,3,5,9,9,10,27.5
530,1,0,0,0,0,0,0,0,0,0,0,0,0,6.978,6.978,5.865,5.865,2,160,23,0.0774,150,0,0,0,640,1,3,5,9,9,13,31.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.24,6.24,6.24,6.24,2,150,17,0.095,130,0,0,0,315,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.304,5.076,5.076,5.076,2,150,13,0.13,150,0,0,0,235,1,3,5,5,5,5,22.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.835,6.041,5.793,7.487,1,150,27,0.05,150,2,0,0,899,0,3,5,9,16,17,38.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.919,6.536,6.536,6.536,1,180,19,0.0795,180,0,0,0,475,1,3,5,9,9,10,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.205,9.205,6.973,6.973,2,190,18,0.0874,190,0,0,0,420,1,3,5,9,9,9,27.5
530,1,0,0,0,0,0,0,0,0,0,0,0,0,11.068,9.512,8.61,8.61,1,190,6,0.0429,190,0,0,0,607,0,3,5,9,9,12,30.0
530,1,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.732,8.399,8.399,2,735,12,0.0741,230,0,0,0,740,0,3,5,9,9,14,32.5
530,1,0,0,0,0,0,0,0,0,0,0,0,0,9.499,8.105,8.106,8.106,1,190,6,0.0508,190,0,0,0,586,0,3,5,9,9,11,27.5
530,1,0,0,0,0,0,0,0,0,0,0,0,0,8.106,6.761,7.748,7.748,2,350,11,0.0909,180,0,0,0,590,0,3,5,8,8,11,28.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.978,5.888,4.736,4.736,2,250,21,0.3134,150,0,0,0,405,1,3,5,9,9,9,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.24,6.24,6.24,6.24,1,130,19,0.3393,130,0,0,0,395,1,3,5,5,5,8,27.5
530,1,0,0,0,0,0,0,0,0,0,0,0,0,6.304,6.095,6.335,6.335,1,150,14,0.0897,150,0,0,0,727,0,3,5,9,9,14,33.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.992,5.064,5.064,5.064,2,190,14,0.2593,190,0,0,0,310,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.919,6.618,7.919,7.919,2,300,17,0.0971,190,0,0,0,735,0,3,5,9,9,13,28.75
530,1,0,0,0,0,0,0,0,0,0,0,0,0,9.205,7.712,9.214,9.214,2,260,15,0.0938,180,0,0,0,689,0,3,5,8,8,12,31.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.006,8.006,8.006,2,230,15,0.4286,210,0,0,0,275,1,3,5,5,5,6,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.006,8.006,8.006,2,230,15,0.4286,210,0,0,0,275,1,3,5,5,5,6,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.499,6.699,6.699,6.699,2,250,15,0.4167,190,0,0,0,275,1,3,5,5,5,6,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.106,5.832,5.832,5.832,2,230,15,0.4412,170,0,0,0,255,1,3,5,5,5,6,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.978,4.947,4.947,4.947,1,150,15,0.4412,150,0,0,0,245,1,3,5,5,5,5,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.24,4.494,4.494,4.494,1,130,11,0.3929,130,0,0,0,205,1,3,5,5,5,5,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.304,6.304,6.304,6.304,2,160,11,0.4231,130,0,0,0,195,1,3,3,3,3,4,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.992,4.897,4.897,4.897,2,180,15,0.4688,150,0,0,0,240,1,3,5,5,5,5,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.919,5.613,5.613,5.613,2,200,15,0.4688,170,0,0,0,240,1,3,5,5,5,5,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.205,6.676,6.676,6.676,2,220,15,0.4412,190,0,0,0,260,1,3,5,5,5,6,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.281,7.083,7.083,2,220,15,0.2344,210,0,0,0,465,1,3,5,9,9,10,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.62,10.184,10.184,2,290,16,0.2133,230,0,0,0,485,1,3,5,9,9,10,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.499,8.619,6.002,6.002,2,430,18,0.2535,170,0,0,0,510,1,3,5,9,9,11,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.106,6.098,6.098,6.098,1,160,15,0.283,160,0,0,0,345,1,3,5,5,5,7,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.978,5.782,5.782,5.782,2,140,16,0.3265,140,0,0,0,330,1,3,5,5,5,7,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.24,5.192,5.192,5.192,2,175,15,0.2727,110,0,0,0,330,1,3,5,5,5,7,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.304,5.076,5.076,5.076,1,110,12,0.4286,110,0,0,0,225,1,3,5,5,5,5,22.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.992,4.89,4.89,4.89,2,160,15,0.4167,130,0,0,0,240,1,3,5,5,5,5,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.919,7.919,5.212,5.212,1,150,18,0.2857,150,0,0,0,495,1,3,5,9,9,10,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.205,7.964,7.964,7.964,2,260,20,0.4348,170,0,0,0,375,1,3,5,5,5,8,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.545,8.545,8.545,2,260,15,0.375,200,0,0,0,290,1,3,5,5,5,6,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.545,8.545,8.545,2,250,12,0.3429,200,0,0,0,265,1,3,5,5,5,6,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.499,6.999,6.999,6.999,2,280,15,0.3571,180,0,0,0,300,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.106,5.943,5.943,5.943,2,220,14,0.3182,160,0,0,0,290,1,3,5,5,5,6,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.978,5.073,5.073,5.073,2,180,13,0.3824,140,0,0,0,230,1,3,5,5,5,5,22.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.24,4.829,4.829,4.829,2,160,13,0.4062,120,0,0,0,210,1,3,5,5,5,5,22.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.304,6.304,6.304,6.304,2,160,12,0.4615,130,0,0,0,190,1,3,3,3,3,4,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.992,5.019,5.019,5.019,2,180,12,0.4286,150,0,0,0,210,1,3,5,5,5,5,22.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.919,5.708,5.708,5.708,2,200,12,0.4,170,0,0,0,230,1,3,5,5,5,5,22.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.205,6.676,6.676,6.676,2,220,12,0.375,190,0,0,0,250,1,3,5,5,5,6,23.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,11.068,9.854,9.537,9.526,1,170,29,0.109,170,5,0,0,1227,0,3,5,9,16,17,47.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,11.068,9.854,9.537,9.526,1,170,29,0.109,170,5,0,0,1227,0,3,5,9,16,17,47.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,9.499,9.499,9.499,9.61,1,150,26,0.1667,150,3,0,0,1025,1,3,5,9,16,17,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,8.106,8.106,8.106,8.185,1,160,38,0.1402,160,6,0,0,1370,1,3,5,9,16,17,52.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,7.11,6.854,6.854,7.468,1,160,25,0.1488,160,3,0,0,999,1,3,5,9,16,17,42.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.651,6.17,5.817,6.278,1,150,28,0.1905,150,3,0,0,1001,1,3,5,9,16,17,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.335,6.095,6.095,5.848,1,150,23,0.1429,150,2,0,0,871,1,3,5,9,16,17,40.0
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.835,6.992,6.992,6.329,1,140,27,0.1731,140,3,0,0,997,1,3,5,9,16,17,42.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,7.876,7.919,7.919,7.423,2,810,26,0.1844,140,2,0,0,1013,1,3,5,9,16,20,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,9.205,9.205,9.205,7.572,1,150,35,0.1296,150,5,0,0,1260,0,3,5,9,16,17,47.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.634,7.226,7.226,2,290,18,0.3,210,0,0,0,415,1,3,5,9,9,9,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.068,8.399,8.399,8.399,2,240,16,0.3721,200,0,0,0,325,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.341,7.068,7.068,7.068,2,210,16,0.3333,210,0,0,0,355,1,3,5,5,5,8,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.106,5.861,5.861,5.861,1,170,15,0.3,170,0,0,0,385,1,3,5,5,5,8,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.978,5.782,5.782,5.782,2,180,16,0.4211,130,0,0,0,245,1,3,5,5,5,5,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.435,4.896,4.896,4.896,2,190,15,0.375,140,0,0,0,275,1,3,5,5,5,6,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.304,4.664,4.664,4.664,2,175,15,0.3846,110,0,0,0,240,1,3,5,5,5,5,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,6.835,4.89,4.89,4.89,2,185,15,0.4286,150,0,0,0,255,1,3,5,5,5,6,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,7.919,5.682,5.682,5.682,2,210,16,0.3636,170,0,0,0,305,1,3,5,5,5,7,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.205,7.164,7.164,7.164,2,230,17,0.3953,150,0,0,0,305,1,3,5,5,5,7,26.25
530,1,0,0,0,0,0,0,0,0,0,1,0,0,11.068,11.068,11.068,10.9,2,170,27,0.1627,170,3,0,0,1058,1,3,5,9,16,17,45.0
530,1,0,0,0,0,0,0,0,0,0,1,0,0,11.068,11.068,11.068,10.9,2,170,27,0.1627,170,3,0,0,1058,1,3,5,9,16,17,45.0
530,1,0,0,0,0,0,0,0,0,0,1,0,0,9.499,9.499,9.499,9.771,2,160,27,0.1776,160,3,0,0,1009,1,3,5,9,16,17,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,8.106,8.106,8.106,8.454,2,150,32,0.1768,150,4,0,0,1103,1,3,5,9,16,17,46.25
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.978,6.978,6.978,7.431,2,140,30,0.2013,140,2,0,0,937,1,3,5,9,16,17,41.25
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.435,6.435,6.435,6.6,1,130,28,0.1795,130,3,0,0,1007,1,3,5,9,16,17,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.304,6.304,6.304,5.728,2,140,22,0.22,140,2,0,0,858,1,3,5,9,16,17,40.0
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.992,6.992,6.992,6.385,2,935,32,0.2207,130,2,0,0,976,1,3,5,9,16,17,42.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,7.919,7.919,7.919,7.888,1,140,29,0.1871,140,3,0,0,1027,1,3,5,9,16,17,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,9.205,9.205,9.205,8.414,2,925,29,0.1986,150,2,0,0,966,1,3,5,9,16,17,42.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,11.068,11.068,11.068,10.9,2,170,27,0.1627,170,3,0,0,1058,1,3,5,9,16,17,45.0
530,1,0,0,0,0,0,0,0,0,0,1,0,0,11.068,11.068,11.068,10.9,2,170,27,0.1627,170,3,0,0,1058,1,3,5,9,16,17,45.0
530,1,0,0,0,0,0,0,0,0,0,1,0,0,9.499,9.499,9.499,9.771,2,160,27,0.1776,160,3,0,0,1009,1,3,5,9,16,17,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,8.106,8.106,8.106,8.454,2,150,32,0.1768,150,4,0,0,1103,1,3,5,9,16,17,46.25
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.978,6.978,6.978,7.431,2,140,30,0.2013,140,2,0,0,937,1,3,5,9,16,17,41.25
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.435,6.435,6.435,6.6,1,130,28,0.1795,130,3,0,0,1007,1,3,5,9,16,17,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.304,6.304,6.304,5.728,2,140,22,0.22,140,2,0,0,858,1,3,5,9,16,17,40.0
530,1,0,0,0,0,0,0,0,0,0,1,0,0,6.992,6.992,6.992,6.385,2,935,32,0.2207,130,2,0,0,976,1,3,5,9,16,17,42.5
530,1,0,0,0,0,0,0,0,0,0,1,0,0,7.919,7.919,7.919,7.888,1,140,29,0.1871,140,3,0,0,1027,1,3,5,9,16,17,43.75
530,1,0,0,0,0,0,0,0,0,0,1,0,0,9.205,9.205,9.205,8.414,2,925,29,0.1986,150,2,0,0,966,1,3,5,9,16,17,42.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,11.586,11.586,1,265,1,0.0047,265,0,0,0,270,0,2,2,2,2,2,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,11.586,11.586,1,265,1,0.0047,265,0,0,0,270,0,2,2,2,2,2,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,10.177,10.177,1,230,1,0.0054,230,0,0,0,235,0,2,2,2,2,2,22.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.677,8.677,8.677,1,200,2,0.0084,200,0,0,0,350,0,2,2,2,2,2,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.062,8.062,8.062,1,190,2,0.0131,190,0,0,0,265,0,2,2,2,2,2,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.133,7.133,7.133,1,140,4,0.0234,140,0,0,0,395,0,2,3,3,3,3,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.051,7.051,7.051,1,140,5,0.0311,140,0,0,0,315,0,2,3,3,3,4,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.544,8.544,8.544,1,190,2,0.0131,190,0,0,0,265,0,2,2,2,2,2,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.573,8.573,8.573,1,190,2,0.0125,190,0,0,0,265,0,2,2,2,2,2,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,10.177,10.177,1,245,1,0.0052,245,0,0,0,250,0,2,2,2,2,2,22.5
390,1,0,0,0,0,0,0,0,0,0,0,1,0,11.828,11.586,10.859,9.958,1,440,35,0.0196,440,0,11,0,1883,0,2,2,4,8,18,62.5
390,1,0,0,0,0,0,0,0,0,0,0,1,0,11.828,11.586,10.859,9.958,1,440,35,0.0196,440,0,11,0,1883,0,2,2,4,8,18,62.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.356,9.356,2,690,8,0.0134,428,0,1,0,700,0,2,2,4,4,6,40.0
390,1,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.056,8.056,1,416,6,0.0109,416,0,1,0,640,0,2,2,4,4,5,37.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.314,7.314,1,404,7,0.0147,404,0,1,0,565,0,2,2,4,4,4,36.25
390,1,0,0,0,0,0,0,0,0,0,0,1,0,8.044,7.711,7.839,6.031,1,392,11,0.0087,392,0,6,0,1357,0,2,2,4,4,4,33.75
390,1,0,0,0,0,0,0,0,0,0,0,1,0,8.044,7.711,6.866,5.612,1,400,16,0.0121,400,0,7,0,1415,0,2,2,4,4,4,36.25
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.454,7.454,2,584,6,0.0109,410,0,0,0,650,0,2,2,4,4,6,37.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.16,8.16,1,416,7,0.0122,416,0,1,0,677,0,2,2,4,4,6,40.0
390,1,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.274,9.274,1,428,7,0.0121,428,0,1,0,666,0,2,2,4,4,5,38.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,11.586,11.586,1,360,1,0.0035,360,0,0,0,385,0,2,2,2,2,2,27.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,11.586,11.586,1,355,1,0.0037,355,0,0,0,360,0,2,2,2,2,3,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,10.177,10.177,1,335,1,0.0041,335,0,0,0,340,0,2,2,2,2,3,26.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.994,8.994,1,265,3,0.0118,265,0,0,0,400,0,2,2,4,4,4,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,8.135,8.135,1,260,2,0.0072,260,0,0,0,360,0,2,2,2,2,2,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.711,7.711,7.711,1,260,1,0.0046,260,0,0,0,265,0,2,2,2,2,2,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.711,7.711,7.711,1,280,1,0.0046,280,0,0,0,285,0,2,2,2,2,2,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,8.135,8.135,1,290,1,0.0034,290,0,0,0,335,0,2,2,2,2,2,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.994,8.994,1,365,1,0.0032,365,0,0,0,370,0,2,2,2,2,2,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,10.177,10.177,1,331,1,0.003,331,0,0,0,375,0,2,2,2,2,2,26.25
390,1,0,0,0,0,0,0,0,0,0,0,3,0,11.828,11.586,10.859,9.13,1,420,20,0.0311,420,0,4,0,950,1,2,2,4,7,10,55.0
390,1,0,0,0,0,0,0,0,0,0,0,3,0,11.828,11.586,10.859,9.13,1,420,20,0.0311,420,0,4,0,950,1,2,2,4,7,10,55.0
390,1,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.356,9.356,2,636,14,0.031,412,0,2,0,709,1,2,2,4,4,4,35.0
390,1,0,0,0,0,0,0,0,0,0,0,2,0,9.295,8.994,8.056,4.511,1,404,19,0.0378,404,0,3,0,838,1,2,2,4,4,4,35.0
390,1,0,0,0,0,0,0,0,0,0,0,2,0,8.46,8.135,7.195,4.415,1,396,19,0.0301,396,0,3,0,939,1,2,2,4,5,5,40.0
390,1,0,0,0,0,0,0,0,0,0,0,2,0,8.044,7.711,6.773,5.589,1,460,20,0.0391,460,0,4,0,877,1,2,2,4,5,5,40.0
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.711,7.839,7.839,1,384,15,0.0367,384,0,3,0,758,1,2,2,4,4,4,32.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.261,7.261,1,400,6,0.0132,400,0,0,0,623,0,2,2,4,4,4,33.75
390,1,0,0,0,0,0,0,0,0,0,0,2,0,9.295,8.994,8.16,7.025,1,410,18,0.0269,410,0,4,0,882,1,2,2,4,7,7,47.5
390,2,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.356,9.576,1,487,17,0.0276,487,0,1,0,893,0,2,2,4,8,9,45.0
390,1,0,0,0,0,0,0,0,0,0,0,2,0,11.828,11.586,10.754,8.469,2,630,21,0.0368,440,0,4,0,898,1,2,2,4,9,10,53.75
390,1,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,10.859,10.859,2,700,24,0.0471,470,0,3,0,770,1,2,2,4,4,8,48.75
390,1,0,0,0,0,0,0,0,0,0,0,2,0,10.449,10.177,9.356,7.437,1,450,15,0.0261,450,0,3,0,865,1,2,2,4,7,8,51.25
390,1,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.017,8.017,2,480,18,0.0424,430,0,1,0,599,1,2,2,4,4,5,40.0
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.913,7.913,1,380,17,0.035,380,0,2,0,745,1,2,2,4,4,7,46.25
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.711,6.905,6.905,1,380,20,0.0449,380,0,2,0,700,1,2,2,4,4,7,45.0
390,1,0,0,0,0,0,0,0,0,0,0,3,0,8.044,7.711,7.382,6.773,2,680,15,0.031,440,0,3,0,855,1,2,2,4,9,10,52.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.913,7.913,1,370,12,0.0228,370,0,3,0,779,1,2,2,4,4,7,45.0
390,1,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.16,8.16,2,490,22,0.0485,450,0,2,0,655,1,2,2,4,4,6,41.25
390,1,0,0,0,0,0,0,0,0,0,0,3,0,10.449,10.177,9.481,7.315,1,450,13,0.0228,450,0,3,0,816,1,2,2,4,7,7,46.25
390,1,0,0,0,0,0,0,0,0,0,0,2,0,11.828,11.586,10.994,10.338,1,450,25,0.0364,450,0,5,0,1084,1,2,2,4,9,13,58.75
390,1,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,10.754,10.754,1,410,2,0.0044,410,0,1,0,657,0,2,2,4,4,5,38.75
390,1,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.274,9.274,1,402,6,0.0118,402,0,1,0,690,0,2,2,4,4,5,37.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.16,8.16,1,430,6,0.0132,430,0,1,0,690,0,2,2,4,4,6,42.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.121,7.121,2,500,16,0.0443,410,0,1,0,535,1,2,2,4,4,5,37.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.711,6.717,6.717,1,410,21,0.0505,410,0,2,0,683,1,2,2,4,4,7,45.0
390,1,0,0,0,0,0,0,0,0,0,0,2,0,8.044,7.711,7.839,4.964,1,382,14,0.0308,382,0,3,0,838,1,2,2,4,4,4,36.25
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.444,7.444,1,420,8,0.0161,420,0,1,0,655,0,2,2,4,4,4,38.75
390,1,0,0,0,0,0,0,0,0,0,0,2,0,9.295,8.994,8.31,6.858,2,893,19,0.0295,430,0,4,0,903,1,2,2,4,7,8,48.75
390,1,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.274,11.358,1,477,7,0.0121,477,0,2,0,835,0,2,2,4,7,7,42.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,11.586,11.586,1,290,1,0.0039,290,0,0,0,385,0,2,2,2,2,2,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,11.586,11.586,1,290,1,0.0039,290,0,0,0,385,0,2,2,2,2,2,25.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,10.177,10.177,1,260,2,0.0083,260,0,0,0,365,0,2,2,2,2,3,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.715,8.715,8.715,1,200,2,0.0117,200,0,0,0,355,0,2,2,2,2,2,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.46,7.756,7.756,7.756,2,280,4,0.0276,140,0,0,0,285,0,2,3,3,3,4,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.044,6.577,6.577,6.577,1,140,4,0.0305,140,0,0,0,300,0,2,3,3,3,4,18.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.044,6.577,6.577,6.577,1,140,4,0.0305,140,0,0,0,300,0,2,3,3,3,4,18.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.46,7.523,7.523,7.523,1,140,5,0.0329,140,0,0,0,325,0,2,3,3,3,4,20.0
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.295,9.472,9.472,9.472,1,210,2,0.0127,210,0,0,0,225,0,2,2,2,2,2,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,10.177,10.177,1,300,1,0.0042,300,0,0,0,310,0,2,2,2,2,2,23.75
390,1,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,10.859,10.859,2,685,22,0.0466,440,0,2,0,705,1,2,2,4,4,7,46.25
390,1,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,10.994,10.994,2,640,22,0.0431,490,0,3,0,785,1,2,2,4,4,8,48.75
390,1,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.481,9.481,2,520,17,0.0403,430,0,1,0,595,1,2,2,4,4,5,40.0
390,1,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.282,8.282,2,610,17,0.0358,360,0,2,0,645,1,2,2,4,4,5,41.25
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.896,7.896,2,570,16,0.0359,380,0,2,0,635,1,2,2,4,4,5,41.25
445,1,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.567,7.044,7.044,1,180,17,0.0318,180,0,2,0,755,1,2,2,3,3,6,43.75
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.711,6.933,6.933,1,420,17,0.0359,420,0,2,0,659,1,2,2,4,4,6,41.25
390,1,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.135,7.444,7.444,2,470,20,0.0368,470,0,3,0,755,1,2,2,4,4,6,45.0
390,1,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.994,8.056,8.056,1,440,22,0.0477,440,0,2,0,665,1,2,2,4,4,6,41.25
390,1,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.356,9.356,1,480,15,0.0315,480,0,2,0,675,1,2,2,4,4,6,41.25
390,1,0,0,0,0,0,0,0,0,0,0,2,0,11.828,11.586,10.859,9.356,2,730,26,0.043,410,0,4,0,982,1,2,2,4,7,11,56.25
390,1,0,0,0,0,0,0,0,0,0,0,2,0,11.828,11.586,10.859,9.356,2,730,26,0.0429,410,0,4,0,985,1,2,2,4,7,11,56.25
390,1,0,0,0,0,0,0,0,0,0,0,2,0,10.449,10.177,9.963,8.479,1,390,20,0.0317,390,0,4,0,904,1,2,2,4,7,8,48.75
390,1,0,0,0,0,0,0,0,0,0,0,0,0,9.295,9.345,9.327,9.327,1,240,2,0.0092,240,0,0,0,500,0,2,2,2,2,2,22.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.062,8.062,8.062,1,190,2,0.0131,190,0,0,0,265,0,2,2,2,2,2,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.133,7.133,7.133,1,140,4,0.0234,140,0,0,0,395,0,2,3,3,3,3,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.044,7.051,7.051,7.051,1,140,5,0.0311,140,0,0,0,315,0,2,3,3,3,4,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,8.46,8.544,8.544,8.544,1,190,2,0.0131,190,0,0,0,265,0,2,2,2,2,2,21.25
0,0,0,0,0,0,0,0,0,0,0,0,0,0,9.295,8.922,8.922,8.922,1,240,1,0.0052,240,0,0,0,275,0,2,2,2,2,2,22.5
390,1,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,9.963,9.963,1,390,6,0.0158,390,0,0,0,605,0,2,2,4,4,5,32.5
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,11.586,11.586,1,265,1,0.0047,265,0,0,0,270,0,2,2,2,2,2,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,11.828,11.586,11.586,11.586,1,265,1,0.0047,265,0,0,0,270,0,2,2,2,2,2,23.75
0,0,0,0,0,0,0,0,0,0,0,0,0,0,10.449,10.177,10.177,10.177,1,230,1,0.0054,230,0,0,0,235,0,2,2,2,2,2,22.5

In [3]:
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

%matplotlib inline

df_raw = pd.read_csv("clusteringTrace.csv", sep=";", engine="python", header=0)

# Clean
df = df_raw.replace("None", pd.NA)
for col in df.columns:
    if df[col].dtype == object:
        df[col] = df[col].str.replace(",", ".", regex=False)

df_numeric = df.apply(pd.to_numeric, errors="coerce")
df_numeric = df_numeric.dropna(axis=1, how="all")   # drop non‑numeric columns

print("Numeric columns:", list(df_numeric.columns))

# Keep only rows that have at least one numeric value (but NOT drop them from df_raw)
valid_rows = df_numeric.dropna(axis=0, how="all")
print("Rows used for clustering:", len(valid_rows))

# Fill NaNs in those rows
valid_filled = valid_rows.fillna(valid_rows.mean(numeric_only=True))

# ----- SCALE THEN WEIGHT FEATURES -----
scaler = StandardScaler()
X_scaled = scaler.fit_transform(valid_filled)

# Put back into a DataFrame so we can edit specific columns
X_df = pd.DataFrame(X_scaled, columns=valid_filled.columns, index=valid_filled.index)

# Downweight FirstBarracks and NumBarracks by factor 0.1
for col in ["FirstBarracks", "NumBarracks"]:
    if col in X_df.columns:
        X_df[col] = X_df[col] * 0.0001

X_weighted = X_df.values

# K-means on weighted features
k = 3
kmeans = KMeans(n_clusters=k, random_state=0)
cluster_labels = kmeans.fit_predict(X_weighted)

# Create a new column in df_raw, default -1, then fill only for valid_rows
df_raw["cluster"] = -1
df_raw.loc[valid_filled.index, "cluster"] = cluster_labels

# Show head
display(df_raw.head())

# Cluster centers in scaled+weighted space
centers = pd.DataFrame(kmeans.cluster_centers_, columns=valid_filled.columns)
print("\nCluster centers (scaled & weighted features):")
display(centers)

# Plot (use same valid rows) - pick any two features that exist
x_feature = "PercentMapHarvested"
y_feature = "AvgAttacksPerTrace"

if x_feature in valid_filled.columns and y_feature in valid_filled.columns:
    plt.figure(figsize=(7, 6))
    sns.scatterplot(
        x=valid_filled[x_feature],
        y=valid_filled[y_feature],
        hue=cluster_labels,
        palette="tab10"
    )
    plt.xlabel(x_feature)
    plt.ylabel(y_feature)
    plt.title(f"K-Means clusters (k={k})")
    plt.legend(title="Cluster")
    plt.tight_layout()
    plt.show()
else:
    print(f"Cannot plot: {x_feature} or {y_feature} not in numeric columns.")

# Make a copy that includes cluster labels, but only for valid rows
clustered = df_raw.loc[valid_filled.index].copy()
clustered["cluster"] = cluster_labels

# 1) Quick view: first few rows with clusters
display(clustered.head())

# 2) Show indices belonging to each cluster
for c in sorted(clustered["cluster"].unique()):
    idx = clustered.index[clustered["cluster"] == c].tolist()
    print(f"\nCluster {c}: row indices {idx}")

# 3) Example: show full rows for cluster 0
cluster_id = 0
display(clustered[clustered["cluster"] == cluster_id])

Numeric columns: ['FirstBarracks            : -1', 'NumBarracks              : 0', 'Light100                 : 0', 'Heavy100                 : 0', 'Ranged100                : 0', 'Light200                 : 0', 'Heavy200                 : 0', 'Ranged200                : 0', 'Light400                 : None', 'Heavy400                 : None', 'Ranged400                : None', 'Light800                 : None', 'Heavy800                 : None', 'Ranged800                : None', 'AvgDist100               : 6.096', 'AvgDist200               : 5.7', 'AvgDist400               : None', 'AvgDist800               : None', 'MaxAttacksSingleTrace    : 1', 'TimeMaxAttacks           : 180', 'TotalAttacks             : 15', 'AvgAttacksPerTrace       : 0.2679', 'FirstAttackTime          : 180', 'TotalLight               : 0', 'TotalHeavy               : 0', 'TotalRanged              : 0', 'GameLength               : 345', 'Player0Win               : 1', 'Workers100               : 2', 'Workers200               : 4', 'Workers400               : None', 'Workers800               : None', 'TotalWorkers ', 'PercentMapHarvested']
Rows used for clustering: 30

,FirstBarracks : -1,NumBarracks : 0,Light100 : 0,Heavy100 : 0,Ranged100 : 0,Light200 : 0,Heavy200 : 0,Ranged200 : 0,Light400 : None,Heavy400 : None,...,TotalRanged : 0,GameLength : 345,Player0Win : 1,Workers100 : 2,Workers200 : 4,Workers400 : None,Workers800 : None,TotalWorkers,PercentMapHarvested,cluster
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,345.0,1.0,2.0,4.0,-1.0,-1.0,6.0,47.5,0
1,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0
2,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,3.0,-1.0,-1.0,7.0,52.5,0
3,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,516.0,1.0,2.0,4.0,7.0,-1.0,10.0,62.5,1
4,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0

Cluster centers (scaled & weighted features):

,FirstBarracks : -1,NumBarracks : 0,Light100 : 0,Heavy100 : 0,Ranged100 : 0,Light200 : 0,Heavy200 : 0,Ranged200 : 0,Light400 : None,Heavy400 : None,...,TotalHeavy : 0,TotalRanged : 0,GameLength : 345,Player0Win : 1,Workers100 : 2,Workers200 : 4,Workers400 : None,Workers800 : None,TotalWorkers,PercentMapHarvested
0,-0.264868,-0.267261,0.0,0.0,0.0,0.0,0.0,0.0,-0.654654,-0.654654,...,0.0,0.0,-0.514155,0.0,0.0,-0.079584,-0.654070,0.0,-0.523084,-0.417070
1,-0.264868,-0.267261,0.0,0.0,0.0,0.0,0.0,0.0,1.527525,1.527525,...,0.0,0.0,0.962468,0.0,0.0,0.185695,1.518377,0.0,1.010565,0.818693
2,3.708158,3.741657,0.0,0.0,0.0,0.0,0.0,0.0,1.527525,1.527525,...,0.0,0.0,2.029988,0.0,0.0,0.185695,1.553416,0.0,1.955401,1.513811

Cannot plot: PercentMapHarvested or AvgAttacksPerTrace not in numeric columns.

,FirstBarracks : -1,NumBarracks : 0,Light100 : 0,Heavy100 : 0,Ranged100 : 0,Light200 : 0,Heavy200 : 0,Ranged200 : 0,Light400 : None,Heavy400 : None,...,TotalRanged : 0,GameLength : 345,Player0Win : 1,Workers100 : 2,Workers200 : 4,Workers400 : None,Workers800 : None,TotalWorkers,PercentMapHarvested,cluster
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,345.0,1.0,2.0,4.0,-1.0,-1.0,6.0,47.5,0
1,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0
2,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,3.0,-1.0,-1.0,7.0,52.5,0
3,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,516.0,1.0,2.0,4.0,7.0,-1.0,10.0,62.5,1
4,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0

Cluster 0: row indices [0, 1, 2, 4, 5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 23, 26, 27, 28, 29]

Cluster 1: row indices [3, 6, 7, 8, 9, 22, 24]

Cluster 2: row indices [21, 25]

,FirstBarracks : -1,NumBarracks : 0,Light100 : 0,Heavy100 : 0,Ranged100 : 0,Light200 : 0,Heavy200 : 0,Ranged200 : 0,Light400 : None,Heavy400 : None,...,TotalRanged : 0,GameLength : 345,Player0Win : 1,Workers100 : 2,Workers200 : 4,Workers400 : None,Workers800 : None,TotalWorkers,PercentMapHarvested,cluster
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,345.0,1.0,2.0,4.0,-1.0,-1.0,6.0,47.5,0
1,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0
2,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,3.0,-1.0,-1.0,7.0,52.5,0
4,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0
5,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,390.0,1.0,2.0,4.0,-1.0,-1.0,7.0,50.0,0
10,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,335.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
11,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,295.0,1.0,2.0,4.0,-1.0,-1.0,5.0,35.0,0
12,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,275.0,1.0,2.0,4.0,-1.0,-1.0,5.0,35.0,0
13,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,335.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
14,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,315.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
15,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,245.0,1.0,2.0,4.0,-1.0,-1.0,4.0,32.5,0
16,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,40.0,0
17,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,345.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
18,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,315.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
19,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,245.0,1.0,2.0,4.0,-1.0,-1.0,4.0,32.5,0
20,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,4.0,-1.0,NaN,7.0,47.5,0
23,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,4.0,-1.0,-1.0,7.0,47.5,0
26,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,355.0,1.0,2.0,4.0,-1.0,-1.0,7.0,45.0,0
27,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,370.0,1.0,2.0,4.0,-1.0,-1.0,7.0,45.0,0
28,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,390.0,1.0,2.0,4.0,-1.0,-1.0,7.0,45.0,0
29,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,330.0,1.0,2.0,4.0,-1.0,-1.0,6.0,42.5,0

In [2]:
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

%matplotlib inline

df_raw = pd.read_csv("clusteringTrace.csv", sep=";", engine="python", header=0)

# Clean
df = df_raw.replace("None", pd.NA)
for col in df.columns:
    if df[col].dtype == object:
        df[col] = df[col].str.replace(",", ".", regex=False)

df_numeric = df.apply(pd.to_numeric, errors="coerce")
df_numeric = df_numeric.dropna(axis=1, how="all")   # drop non‑numeric columns

print("Numeric columns (before drop):", list(df_numeric.columns))

# Keep only rows that have at least one numeric value
valid_rows = df_numeric.dropna(axis=0, how="all")
print("Rows used for clustering:", len(valid_rows))

# Fill NaNs in those rows
valid_filled = valid_rows.fillna(valid_rows.mean(numeric_only=True))

# ---- DROP UNWANTED COLUMNS FOR CLUSTERING ----
cols_to_drop = [
    "Light100", "Light200", "Light400",
    "Heavy100", "Heavy200", "Heavy400",
    "Ranged100", "Ranged200", "Ranged400",
    "Player0Win", "FirstBarracks", "NumBarracks",
]

existing_drop = [c for c in cols_to_drop if c in valid_filled.columns]
print("Dropping from clustering:", existing_drop)

valid_filled = valid_filled.drop(columns=existing_drop)

print("Numeric columns (used for clustering):", list(valid_filled.columns))

# ----- SCALE FEATURES -----
scaler = StandardScaler()
X_scaled = scaler.fit_transform(valid_filled)

X_df = pd.DataFrame(X_scaled, columns=valid_filled.columns, index=valid_filled.index)

# (no need to downweight FirstBarracks/NumBarracks now, they are removed)

X_weighted = X_df.values

# K-means on selected features
k = 3
kmeans = KMeans(n_clusters=k, random_state=0)
cluster_labels = kmeans.fit_predict(X_weighted)

# Create a new column in df_raw, default -1, then fill only for valid_rows
df_raw["cluster"] = -1
df_raw.loc[valid_filled.index, "cluster"] = cluster_labels

# Show head
display(df_raw.head())

# Cluster centers in scaled feature space
centers = pd.DataFrame(kmeans.cluster_centers_, columns=valid_filled.columns)
print("\nCluster centers (scaled features):")
display(centers)

# Plot (use same valid rows) - pick any two features that exist
x_feature = "PercentMapHarvested"
y_feature = "AvgAttacksPerTrace"

if x_feature in valid_filled.columns and y_feature in valid_filled.columns:
    plt.figure(figsize=(7, 6))
    sns.scatterplot(
        x=valid_filled[x_feature],
        y=valid_filled[y_feature],
        hue=cluster_labels,
        palette="tab10"
    )
    plt.xlabel(x_feature)
    plt.ylabel(y_feature)
    plt.title(f"K-Means clusters (k={k})")
    plt.legend(title="Cluster")
    plt.tight_layout()
    plt.show()
else:
    print(f"Cannot plot: {x_feature} or {y_feature} not in numeric columns.")
    print("Available:", list(valid_filled.columns))

# Make a copy that includes cluster labels, but only for valid rows
clustered = df_raw.loc[valid_filled.index].copy()
clustered["cluster"] = cluster_labels

# 1) Quick view: first few rows with clusters
display(clustered.head())

# 2) Show indices belonging to each cluster
for c in sorted(clustered["cluster"].unique()):
    idx = clustered.index[clustered["cluster"] == c].tolist()
    print(f"\nCluster {c}: row indices {idx}")

# 3) Example: show full rows for cluster 0
cluster_id = 0
display(clustered[clustered["cluster"] == cluster_id])

Numeric columns (before drop): ['FirstBarracks            : -1', 'NumBarracks              : 0', 'Light100                 : 0', 'Heavy100                 : 0', 'Ranged100                : 0', 'Light200                 : 0', 'Heavy200                 : 0', 'Ranged200                : 0', 'Light400                 : None', 'Heavy400                 : None', 'Ranged400                : None', 'Light800                 : None', 'Heavy800                 : None', 'Ranged800                : None', 'AvgDist100               : 6.096', 'AvgDist200               : 5.7', 'AvgDist400               : None', 'AvgDist800               : None', 'MaxAttacksSingleTrace    : 1', 'TimeMaxAttacks           : 180', 'TotalAttacks             : 15', 'AvgAttacksPerTrace       : 0.2679', 'FirstAttackTime          : 180', 'TotalLight               : 0', 'TotalHeavy               : 0', 'TotalRanged              : 0', 'GameLength               : 345', 'Player0Win               : 1', 'Workers100               : 2', 'Workers200               : 4', 'Workers400               : None', 'Workers800               : None', 'TotalWorkers ', 'PercentMapHarvested']
Rows used for clustering: 30
Dropping from clustering: []
Numeric columns (used for clustering): ['FirstBarracks            : -1', 'NumBarracks              : 0', 'Light100                 : 0', 'Heavy100                 : 0', 'Ranged100                : 0', 'Light200                 : 0', 'Heavy200                 : 0', 'Ranged200                : 0', 'Light400                 : None', 'Heavy400                 : None', 'Ranged400                : None', 'Light800                 : None', 'Heavy800                 : None', 'Ranged800                : None', 'AvgDist100               : 6.096', 'AvgDist200               : 5.7', 'AvgDist400               : None', 'AvgDist800               : None', 'MaxAttacksSingleTrace    : 1', 'TimeMaxAttacks           : 180', 'TotalAttacks             : 15', 'AvgAttacksPerTrace       : 0.2679', 'FirstAttackTime          : 180', 'TotalLight               : 0', 'TotalHeavy               : 0', 'TotalRanged              : 0', 'GameLength               : 345', 'Player0Win               : 1', 'Workers100               : 2', 'Workers200               : 4', 'Workers400               : None', 'Workers800               : None', 'TotalWorkers ', 'PercentMapHarvested']

,FirstBarracks : -1,NumBarracks : 0,Light100 : 0,Heavy100 : 0,Ranged100 : 0,Light200 : 0,Heavy200 : 0,Ranged200 : 0,Light400 : None,Heavy400 : None,...,TotalRanged : 0,GameLength : 345,Player0Win : 1,Workers100 : 2,Workers200 : 4,Workers400 : None,Workers800 : None,TotalWorkers,PercentMapHarvested,cluster
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,345.0,1.0,2.0,4.0,-1.0,-1.0,6.0,47.5,0
1,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0
2,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,3.0,-1.0,-1.0,7.0,52.5,0
3,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,516.0,1.0,2.0,4.0,7.0,-1.0,10.0,62.5,1
4,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0

Cluster centers (scaled features):

,FirstBarracks : -1,NumBarracks : 0,Light100 : 0,Heavy100 : 0,Ranged100 : 0,Light200 : 0,Heavy200 : 0,Ranged200 : 0,Light400 : None,Heavy400 : None,...,TotalHeavy : 0,TotalRanged : 0,GameLength : 345,Player0Win : 1,Workers100 : 2,Workers200 : 4,Workers400 : None,Workers800 : None,TotalWorkers,PercentMapHarvested
0,-0.264868,-0.267261,0.0,0.0,0.0,0.0,0.0,0.0,-0.654654,-0.654654,...,0.0,0.0,-0.514155,0.0,0.0,-0.079584,-0.654070,0.0,-0.523084,-0.417070
1,-0.264868,-0.267261,0.0,0.0,0.0,0.0,0.0,0.0,1.527525,1.527525,...,0.0,0.0,0.962468,0.0,0.0,0.185695,1.518377,0.0,1.010565,0.818693
2,3.708158,3.741657,0.0,0.0,0.0,0.0,0.0,0.0,1.527525,1.527525,...,0.0,0.0,2.029988,0.0,0.0,0.185695,1.553416,0.0,1.955401,1.513811

Cannot plot: PercentMapHarvested or AvgAttacksPerTrace not in numeric columns.
Available: ['FirstBarracks            : -1', 'NumBarracks              : 0', 'Light100                 : 0', 'Heavy100                 : 0', 'Ranged100                : 0', 'Light200                 : 0', 'Heavy200                 : 0', 'Ranged200                : 0', 'Light400                 : None', 'Heavy400                 : None', 'Ranged400                : None', 'Light800                 : None', 'Heavy800                 : None', 'Ranged800                : None', 'AvgDist100               : 6.096', 'AvgDist200               : 5.7', 'AvgDist400               : None', 'AvgDist800               : None', 'MaxAttacksSingleTrace    : 1', 'TimeMaxAttacks           : 180', 'TotalAttacks             : 15', 'AvgAttacksPerTrace       : 0.2679', 'FirstAttackTime          : 180', 'TotalLight               : 0', 'TotalHeavy               : 0', 'TotalRanged              : 0', 'GameLength               : 345', 'Player0Win               : 1', 'Workers100               : 2', 'Workers200               : 4', 'Workers400               : None', 'Workers800               : None', 'TotalWorkers ', 'PercentMapHarvested']

,FirstBarracks : -1,NumBarracks : 0,Light100 : 0,Heavy100 : 0,Ranged100 : 0,Light200 : 0,Heavy200 : 0,Ranged200 : 0,Light400 : None,Heavy400 : None,...,TotalRanged : 0,GameLength : 345,Player0Win : 1,Workers100 : 2,Workers200 : 4,Workers400 : None,Workers800 : None,TotalWorkers,PercentMapHarvested,cluster
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,345.0,1.0,2.0,4.0,-1.0,-1.0,6.0,47.5,0
1,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0
2,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,3.0,-1.0,-1.0,7.0,52.5,0
3,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,516.0,1.0,2.0,4.0,7.0,-1.0,10.0,62.5,1
4,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0

Cluster 0: row indices [0, 1, 2, 4, 5, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 23, 26, 27, 28, 29]

Cluster 1: row indices [3, 6, 7, 8, 9, 22, 24]

Cluster 2: row indices [21, 25]

,FirstBarracks : -1,NumBarracks : 0,Light100 : 0,Heavy100 : 0,Ranged100 : 0,Light200 : 0,Heavy200 : 0,Ranged200 : 0,Light400 : None,Heavy400 : None,...,TotalRanged : 0,GameLength : 345,Player0Win : 1,Workers100 : 2,Workers200 : 4,Workers400 : None,Workers800 : None,TotalWorkers,PercentMapHarvested,cluster
0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,345.0,1.0,2.0,4.0,-1.0,-1.0,6.0,47.5,0
1,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0
2,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,3.0,-1.0,-1.0,7.0,52.5,0
4,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,52.5,0
5,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,390.0,1.0,2.0,4.0,-1.0,-1.0,7.0,50.0,0
10,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,335.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
11,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,295.0,1.0,2.0,4.0,-1.0,-1.0,5.0,35.0,0
12,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,275.0,1.0,2.0,4.0,-1.0,-1.0,5.0,35.0,0
13,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,335.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
14,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,315.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
15,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,245.0,1.0,2.0,4.0,-1.0,-1.0,4.0,32.5,0
16,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,375.0,1.0,2.0,4.0,-1.0,-1.0,7.0,40.0,0
17,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,345.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
18,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,315.0,1.0,2.0,4.0,-1.0,-1.0,6.0,37.5,0
19,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,245.0,1.0,2.0,4.0,-1.0,-1.0,4.0,32.5,0
20,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,4.0,-1.0,NaN,7.0,47.5,0
23,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,385.0,1.0,2.0,4.0,-1.0,-1.0,7.0,47.5,0
26,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,355.0,1.0,2.0,4.0,-1.0,-1.0,7.0,45.0,0
27,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,370.0,1.0,2.0,4.0,-1.0,-1.0,7.0,45.0,0
28,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,390.0,1.0,2.0,4.0,-1.0,-1.0,7.0,45.0,0
29,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0,...,0.0,330.0,1.0,2.0,4.0,-1.0,-1.0,6.0,42.5,0